stages:
  - load
  - build
  - test
  - show_log_on_failure
  - cleanup

load_local:
  stage: load
  before_script:
    - export PATH=$PATH:/usr/bin
  script:
    - ls -la
    - hostname
    - docker run -v config/influxdb_local/:/etc/influxdb/ -p "8086:8086" -p "8088:8088" --name influxdb_local influxdb:latest

load_remote:
  stage: load
  script:
    - docker run -v config/influxdb_local/:/etc/influxdb/ -p "8090:8086" -p "8094:8088" --name influxdb_remote influxdb:latest

load_telegraf:
  stage: load
  script:
    - docker run  -v config/telegraf/:/etc/telegraf/ --link influxdb_remote:influxdb_remote --name telegraf telegraf:latest

build_gateway:
  stage: build
  script:
    - docker build -t influx_gateway .

test_gateway:
  stage: test
  retry: 2
  script:
    - docker rm -vf influx_gateway || true
    - docker run  --link influxdb_local --link influxdb_remote influx_gateway --name influx_gateway

show_log:
  stage: show_log_on_failure
  script:
    - echo "Influx_gateway_log"
    - docker log influx_gateway
  when: on_failure

cleanup:
  stage: cleanup
  script:
    - docker rm -vf influxdb_local || true
    - docker rm -vf influxdb_remote || true
    - docker rm -vf telegraf || true
    - docker rm -vf influx_gateway || true

