stages:
  - pre-cleanup
  - load
  - build
  - test
  - show_log_on_failure
  - artifact
  - cleanup

pre-run-cleanup:
  stage: pre-cleanup
  script:
    - docker rm -vf influxdb_local || true
    - docker rm -vf influxdb_remote || true
    - docker rm -vf telegraf || true
    - docker rm -vf influx_gateway || true
    - sudo apt-get install -qy dpkg debconf debhelper lintian hashdeep
  when: always
  only:
    - tags

load_local:
  stage: load
  before_script:
    - export PATH=$PATH:/usr/bin
  script:
    - docker rm -vf influxdb_local || true
    - docker run -d  --name influxdb_local -v "$PWD/config/influxdb_local/:/etc/influxdb/" influxdb:latest
  only:
    - tags

load_remote:
  stage: load
  script:
    - docker rm -vf influxdb_remote || true
    - docker run -d --name influxdb_remote -v "$PWD/config/influxdb_local/:/etc/influxdb/" influxdb:latest
  only:
    - tags

load_telegraf:
  stage: load
  script:
    - docker rm -vf telegraf || true
    - docker run  -d --name telegraf -v "$PWD/config/telegraf/:/etc/telegraf/" --link influxdb_remote:influxdb_remote telegraf:latest
  only:
    - tags

build_gateway:
  stage: build
  script:
    - docker build -t influx_gateway .
  only:
    - tags

test_gateway:
  stage: test
  retry: 1
  script:
    - docker rm -vf influx_gateway || true
    - sleep 3
    - docker run  --name influx_gateway --link influxdb_local:influxdb_local --link influxdb_remote:influxdb_remote influx_gateway
  only:
    - tags

show_log:
  stage: show_log_on_failure
  script:
    - echo "Influx_gateway_log"
    - docker logs influx_gateway
  when: on_failure
  only:
    - tags

tar_archive:
  stage: artifact
  script:
    - mkdir -p artifact
    - docker cp influx_gateway:/influx_gateway/influx_gw.py artifact/
    - docker cp influx_gateway:/influx_gateway/tasks.py artifact/
    - docker cp influx_gateway:/influx_gateway/example/config.json artifact/
    - docker cp influx_gateway:/influx_gateway/README.md artifact/
    - docker cp influx_gateway:/influx_gateway/requirements.txt artifact/
    - tar -cvf influx_gateway_${CI_COMMIT_TAG}.tar -C artifact .

  artifacts:
    name: influx_gateway_${CI_COMMIT_TAG}.tar
    paths:
      - influx_gateway_${CI_COMMIT_TAG}.tar
  only:
#    - master
#    - developer
    - tags

deb_package:
  stage: artifact
  script:
    - mkdir influx-gw
    - mkdir influx-gw/DEBIAN
    - mkdir -p influx-gw/usr/local/share/influx-gw
    - docker cp influx_gateway:/influx_gateway/influx_gw.py influx-gw/usr/local/share/influx-gw
    - docker cp influx_gateway:/influx_gateway/tasks.py influx-gw/usr/local/share/influx-gw
    - docker cp influx_gateway:/influx_gateway/example/config.json influx-gw/usr/local/share/influx-gw
    - docker cp influx_gateway:/influx_gateway/README.md influx-gw/usr/local/share/influx-gw
    - docker cp influx_gateway:/influx_gateway/requirements.txt influx-gw/usr/local/share/influx-gw
    - docker cp influx_gateway:/influx_gateway/DEBIAN/control influx-gw/DEBIAN/
    - docker cp influx_gateway:/influx_gateway/DEBIAN/cron.d influx-gw/DEBIAN/
    - docker cp influx_gateway:/influx_gateway/DEBIAN/dirs influx-gw/DEBIAN/
    - docker cp influx_gateway:/influx_gateway/DEBIAN/postinst influx-gw/DEBIAN/
    - md5deep -r influx-gw/usr > influx-gw/DEBIAN/md5sums
    - chmod a+x influx-gw/DEBIAN/postinst
    - fakeroot dpkg-deb --build influx-gw
    - mv influx-gw.deb influx-gw_${CI_COMMIT_TAG}_all.deb
  artifacts:
    name: influx-gw_${CI_COMMIT_TAG}_all.deb
    paths:
      - influx-gw_${CI_COMMIT_TAG}_all.deb
  only:
#    - master
#    - developer
    - tags

cleanup:
  stage: cleanup
  script:
    - docker rm -vf influxdb_local || true
    - docker rm -vf influxdb_remote || true
    - docker rm -vf telegraf || true
    - docker rm -vf influx_gateway || true
    - rm -rf artifact
    - rm -rf influx-gw*
  when: always
  only:
    - tags
