language: python
sudo: required
dist: trusty

python:
   - "3.6"

before_install:
  - curl -sSL "https://get.docker.com/gpg" | sudo -E apt-key add -
  - echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --assume-yes install docker-engine
  - docker version
  - sudo pip install docker-compose
  - docker-compose version
  - docker-compose pull
  - docker-compose build
  - docker-compose start
  - docker ps

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - pytest