version: '3'
services:
  influxdb_local:
    container_name: influxdb_local
    image: influxdb:latest
    ports:
      - "8086:8086"
      - "8088:8088"
    volumes:
      - ./config/influxdb_local:/etc/influxdb/

  influxdb_remote:
    container_name: influxdb_remote
    image: influxdb:latest
    ports:
      - "8090:8086"
      - "8094:8088"
    volumes:
      - ./config/influxdb_remote:/etc/influxdb/

  telegraf:
    container_name: telegraf
    image: telegraf:latest
    volumes:
      - ./config/telegraf/:/etc/telegraf/
    depends_on:
      - influxdb_remote
    links:
      - "influxdb_remote:influxdb_remote"
